
python_2_6_tests:
  image: centos:6
  script:
    - yum -y update && yum clean all
    - yum -y install scipy numpy
    # some tests fail with numpy-1.4, use a newer version
    - easy_install pip wheel
    - pip install numpy==1.6.2
    - pwd
    - echo $HOME
    - cd ..
    - echo $PWD
    # using 'install from source' instructions
    - export PATH=$PATH:$CI_PROJECT_DIR/tools
    - echo $PATH
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo $PYTHONPATH
    # tests
    - python --version
    # module can't be executed as script on py 2.6
    - python -m ase.test.__main__

python_2_7_tests:
  script:
    - apt-get update -qy
    - apt-get install -qy python-numpy python-scipy pyflakes
    - pwd
    - echo $HOME
    - cd ..
    - echo $PWD
    # using 'install from source' instructions
    - export PATH=$PATH:$CI_PROJECT_DIR/tools
    - echo $PATH
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo $PYTHONPATH
    # tests
    - python --version
    - python -m ase.test
    # pyflakes code check
    - cd $CI_PROJECT_DIR
    - PYTHONPATH=$PWD python ase/test/__init__.py

python_3_tests:
  script:
    - apt-get update -qy
    - apt-get install -qy python3-pip python3-numpy python3-scipy pyflakes gettext
    # install ase into current python environment to ensure
    # any shebang lines in scripts point to python3
    - pip3 install --user .
    # script path when installing with --user
    - export PATH=$HOME/.local/bin:$PATH
    # Running from a temporary directory to avoid import errors
    - mkdir -p /tmp/test/ && cd /tmp/test && echo $PWD
    # Run tests
    - python3 --version
    - python3 -m ase.test
    # pyflakes code check
    - cd $CI_PROJECT_DIR
    - python3 ase/test/__init__.py
