master:
  script:
    - apt-get update -qy
    - apt-get install -qy python-numpy python-scipy pyflakes
    - pwd
    - echo $HOME
    - echo $PWD
    - echo $PYTHONPATH
    - cd ..
    - PATH=$PATH:$PWD/ase/tools PYTHONPATH=$PWD/ase python -m ase.test
    - cd ase
    - PYTHONPATH=$PWD python ase/test/__init__.py
