line-length = 80
exclude = ["./build/", "./dist", "./doc/build"]
src = ["ase"]

[lint]
select = ["E4", "E7", "E9", "F", "B"]
ignore = ["E741"]

[format]
quote-style = "single"
skip-magic-trailing-comma = false

[pycodestyle]
max-line-length = 80
max-doc-length = 80

[pydocstyle]
convention = "numpy"

[isort]
known-first-party = ["ase"]