line-length = 80
exclude = ["./build/", "./dist", "ase/cli/complete.py", "./doc/build"]
src = ["ase"]

[lint]
select = ["E", "F", "B"]
ignore = ["E741"]
fixable = ["ALL"]

[format]
quote-style = "single"
skip-magic-trailing-comma = false

[pycodestyle]
max-line-length = 80
max-doc-length = 80

[pydocstyle]
convention = "numpy"

[isort]
known-first-party = ["ase"]
